export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGIN_FAIL = "AUTH/LOGIN_FAIL";
export const REGISTER_HEADER = "HEADER/REGISTER_HEADER";
export const LOGIN_HEADER = "HEADER/LOGIN_HEADER";
export const AUTHENTICATED_HEADER = "HEADER/AUTHENTICATED_HEADER";
export const ANON_HEADER = "HEADER/ANON_HEADER";
