# Generated by Django 3.2.12 on 2022-02-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_optional_bio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
