# Generated by Django 3.2.12 on 2022-02-16 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='class name')),
            ],
            options={
                'verbose_name': 'character class',
                'verbose_name_plural': 'character classes',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='race name')),
            ],
            options={
                'verbose_name': 'character race',
                'verbose_name_plural': 'character races',
            },
        ),
        migrations.CreateModel(
            name='PlayableCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='character name')),
                ('max_hp', models.IntegerField(default=10, verbose_name='character max hp')),
                ('armor_class', models.IntegerField(default=5, verbose_name='armor class')),
                ('level', models.IntegerField(default=1, verbose_name='character level')),
                ('strength', models.IntegerField(default=10, verbose_name='character strength')),
                ('dexterity', models.IntegerField(default=10, verbose_name='character dexterity')),
                ('constitution', models.IntegerField(default=10, verbose_name='character constitution')),
                ('intelligence', models.IntegerField(default=10, verbose_name='character intelligence')),
                ('wisdom', models.IntegerField(default=10, verbose_name='character wisdom')),
                ('charisma', models.IntegerField(default=10, verbose_name='character charisma')),
                ('speed', models.IntegerField(default=30, verbose_name='character speed')),
                ('temporary_hp', models.IntegerField(default=0, verbose_name='temporary character')),
                ('initiative_bonus', models.IntegerField(default=2, verbose_name='initiative bonus')),
                ('clazz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.characterclass', verbose_name='character class')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='character owner')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.race', verbose_name='character race')),
            ],
            options={
                'verbose_name': 'playable character',
                'verbose_name_plural': 'playable characters',
            },
        ),
    ]
