# Generated by Django 3.2.12 on 2022-02-16 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_base_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playablecharacter',
            name='clazz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='characters.characterclass', verbose_name='character class'),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='characters.race', verbose_name='character race'),
        ),
        migrations.AlterField(
            model_name='playablecharacter',
            name='temporary_hp',
            field=models.IntegerField(default=0, verbose_name='temporary hp'),
        ),
    ]
