# Generated by Django 3.2.12 on 2022-02-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_related_names_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playablecharacter',
            old_name='clazz',
            new_name='class',
        ),
    ]
