# Generated by Django 3.2.12 on 2022-02-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_characters_class_rename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playablecharacter',
            old_name='class',
            new_name='clazz',
        ),
    ]
