# Generated by Django 3.2.12 on 2022-02-26 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0006_auto_20220218_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayableCharacter',
            new_name='Character',
        ),
    ]
